# Generated by Django 6.1.1 on 2026-10-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataAccess', '0009_firereport_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Departed', 'Departed'), ('Arrived', 'Arrived'), ('Returned', 'Returned')], default='Ordered', max_length=20)),
                ('route', models.JSONField(blank=True, default=dict)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='DataAccess.firereport')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('task', models.CharField(max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duties', to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField()),
                ('snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('Submitted', 'Submitted'), ('Revision', 'Revision'), ('Approved', 'Approved')], default='Submitted', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_report', to='DataAccess.firereport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='DataAccess.user')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='DataAccess.firereport')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='DataAccess.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acting_assignments', to='DataAccess.user')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Emergency.leave')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firereport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('Public', 'လူတိုင်း'), ('Staff', 'ဝန်ထမ်းအားလုံး'), ('Station', 'မိမိစခန်း')], max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'နယ်မြေခံ'), (1, 'အဆင့် ၁'), (2, 'အဆင့် ၂'), (3, 'အဆင့် ၃'), (4, 'အဆင့် ၄'), (5, 'အဆင့် ၅')])),
                ('home_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_plans', to='DataAccess.firestation')),
                ('lead_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='DataAccess.firestation')),
            ],
        ),
        migrations.CreateModel(
            name='RoadEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metres', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='Emergency.roadnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='Emergency.roadnode')),
            ],
        ),
        migrations.CreateModel(
            name='StaffParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('actual', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='Emergency.deployment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField()),
                ('water_gallons', models.DecimalField(decimal_places=2, max_digits=12)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='station_report', to='Emergency.deployment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Deployed', 'Deployed'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Available', max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emergency.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('actual', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='Emergency.deployment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emergency.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DataAccess.firestation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='Emergency.responseplan')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Emergency.vehicletype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(fields=('incident', 'station'), name='unique_incident_station'),
        ),
        migrations.AddConstraint(
            model_name='responseplan',
            constraint=models.UniqueConstraint(fields=('home_station', 'level'), name='unique_home_level'),
        ),
        migrations.AddConstraint(
            model_name='planrequirement',
            constraint=models.UniqueConstraint(fields=('plan', 'station', 'kind'), name='unique_plan_resource'),
        ),
        migrations.AddConstraint(
            model_name='planrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_plan_quantity'),
        ),
    ]
