# Generated by Django 6.1.1 on 2026-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deployment',
            name='unique_incident_station',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='state',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Accepted', 'Accepted'), ('Departed', 'Departed'), ('Arrived', 'Arrived'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=20),
        ),
    ]
