# Generated by Django 6.1.1 on 2026-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emergency', '0002_remove_deployment_unique_incident_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyanmarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('township', 'Township'), ('town', 'Town')], max_length=10)),
                ('name_en', models.CharField(max_length=150)),
                ('name_my', models.CharField(blank=True, max_length=150)),
                ('region_pcode', models.CharField(max_length=20)),
                ('region_name_en', models.CharField(max_length=100)),
                ('district_pcode', models.CharField(max_length=20)),
                ('district_name_en', models.CharField(max_length=100)),
                ('township_pcode', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['kind', 'name_en'],
            },
        ),
    ]
