# Generated by Django 6.1.1 on 2026-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0006_fire_scale_6_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
