# Generated by Django 6.1.1 on 2026-10-06 19:37

import django.db.models.deletion
from django.db import migrations, models


def prepare_unique_phones(apps, schema_editor):
    users = apps.get_model('DataAccess', 'User').objects.using(schema_editor.connection.alias)
    users.filter(phone_number='').update(phone_number=None)
    duplicates = users.exclude(phone_number=None).values('phone_number').annotate(total=models.Count('pk')).filter(total__gt=1)
    if duplicates.exists():
        raise RuntimeError('Existing accounts share phone numbers. Assign distinct phone numbers before applying this migration; account history is preserved.')


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0008_localize_burmese_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='firereport',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firereport',
            name='coordinates_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firereport',
            name='home_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_incidents', to='DataAccess.firestation'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='lead_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='led_incidents', to='DataAccess.firestation'),
        ),
        migrations.AddField(
            model_name='firereport',
            name='reporter_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firereport',
            name='reporter_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='nrc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='DataAccess.firestation'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='fire_scale',
            field=models.IntegerField(choices=[(0, 'နယ်မြေခံ'), (1, 'အဆင့် ၁'), (2, 'အဆင့် ၂'), (3, 'အဆင့် ၃'), (4, 'အဆင့် ၄'), (5, 'အဆင့် ၅')], help_text='Severity Scale: 0=နယ်မြေခံ, 1=Level 1, 2=Level 2, 3=Level 3, 4=Level 4, 5=Level 5'),
        ),
        migrations.AlterField(
            model_name='firereport',
            name='status',
            field=models.CharField(choices=[('Pending', 'ဆိုင်းငံ့ / စိစစ်ဆဲ'), ('Confirmed', 'အတည်ပြုပြီး'), ('Dispatched', 'တပ်ဖွဲ့စေလွှတ်ပြီး'), ('Under Control', 'မီးထိန်းချုပ်နိုင်ပြီ'), ('Resolved', 'ငြှိမ်းသတ်ပြီးစီး'), ('False Alarm', 'သတင်းမှား')], default='Pending', help_text='Current status of the fire incident response', max_length=20),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='status',
            field=models.CharField(choices=[('Active', 'အသင့်ရှိ'), ('Inactive', 'ယာယီပိတ်ထား'), ('Maintenance', 'ပြုပြင်ထိန်းသိမ်းဆဲ')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(prepare_unique_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'အသုံးပြုဆဲ'), ('Suspended', 'ယာယီရပ်ဆိုင်း'), ('Inactive', 'ပိတ်ထား')], default='Active', max_length=20),
        ),
    ]
