# Generated by Django 6.1.1 on 2026-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccess', '0010_firestation_township'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='firestation',
            name='source_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firestation',
            name='status',
            field=models.CharField(choices=[('Active', 'အသင့်ရှိ'), ('Unknown', 'အသင့်ရှိမှု မစစ်ဆေးရသေး'), ('Inactive', 'ယာယီပိတ်ထား'), ('Maintenance', 'ပြုပြင်ထိန်းသိမ်းဆဲ')], default='Active', max_length=20),
        ),
    ]
